---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if nginx is running
      ansible.builtin.service:
        name: nginx
        state: started
      tags:
        - ansible
        - builtin
        - service
      register: reg_service_nginx

    - name: Assert nginx running
      ansible.builtin.assert:
        that: reg_service_nginx.state == 'started'
